spring:
  application:
    name: user
    version: 1.0.0
  output:
    ansi:
      enabled: ALWAYS
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      lifetime-minutes: 90
  server:
    client-auth: WANT
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gaia-key.pfx
    key-store-password:
    protocol: TLS

api:
  support-user:
    base-path: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,loggers